spring.application.name=C5

spring.datasource.url=jdbc:postgresql://23.88.104.53:8060/db_metas
spring.datasource.username=admin
spring.datasource.password=4R9b2z
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


